### ISSUE TITLE
Recaps sources

### ISSUE THREAD

**Issue by M0ns1gn0r** [victor-homyakov/recaps#2]
The README states this is the same tool which was written by Eli Golovinsky http://www.gooli.org/

Can you explain how you acquired the tool's source files? Are they authentic?

**Comment by victor-homyakov** [comment]
http://www.gooli.org/blog/recaps/

> Recaps is released under the GNU GPL license.
> 
> Downloads
> - A source archive you can tinker with and build yourself with VS2005.
> 
> News
> - 2008/05/18 – Recaps 0.6 released – added ability to correct text typed with the wrong keyboard layout.

Everyone could download the sources and check their authenticity (except formatting and pieces of code I've added since then).

**Comment by M0ns1gn0r** [comment]
Thanks, so this repository was created from the attached source codes.
